### ISSUE TITLE
Implement staking for token issuance

### ISSUE THREAD

**Issue by yagizsenal** [yigitsever/gradecoin#2]
In current implementation, bots create transaction requests to send back the coins that are sent to them in the last confirmed block. Also, new tokens are issued in every confirmed transaction. Instead of this, we can implement [staking](https://www.coinbase.com/learn/crypto-basics/what-is-staking) which will issue a percentage of the amount staked by the user and send back to them after `T` seconds.

**Comment by yigitsever** [comment]
To my understanding, 'staking' (within the game environment) is similar to the current behaviour of "send coin get coin" but now it would be "send coin get percentage back".

I think this is straightforward to implement, can go through `/transaction` endpoint (transactions to bots are always to stake) or a new endpoint `/stake` could be created. Would clean up the `propose_transaction` function over at: 

https://github.com/yigitsever/gradecoin/blob/fd24f0730c8d429730d324b02882916b3e579a2d/src/handlers.rs#L649 

Which handles transactions to bots & transactions to people at the same place.

I can take a look at this when a get a chance, if you'd like to contribute please let me know and you can send a PR.

**Comment by yagizsenal** [comment]
Yes, there is little change to be made in the current system to implement this feature. I actually proposed this because the term "staking" felt more "crypto-native" to me.

Since the changes required are minimal, I think this is a good first issue. Therefore I will try to implement it and send a PR.
