### ISSUE TITLE
Switching between modes of operation

### ISSUE THREAD

**Issue by yigitsever** [yigitsever/gradecoin#4]
The game/simulation is assigned in two phases. During the first "testnet" phase students are expected to get themselves familiarized with the API and authentication. The system is restarted and the "realnet" phase begins. Ideally, these two phases have different rules so there's something to look forward to. The modes should also be changed between different semesters (different offerings of the course). 

Currently, this is handled manually using git branches or commenting/uncommenting and copy & pasting. A more robust solution might look like a command line or environment variable that sets the rules of the game according to the mode. Codebase probably requires heavy refactoring to allow this as well.

**Comment by yagizsenal** [comment]
Maybe we can load every aspect of the system from a configuration file (a.k.a `yaml`) and add different configuration files for different modes of the system.

I would also like to see mainnet and testnet running at the same time. Former being where everything has a real value and latter being a free playground for every aspect of the system.
